//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdemeProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAbone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAbone()
        {
            this.AboneDurum = true;
            this.DepozitoTutari = 500m;
            this.tblFatura = new HashSet<tblFatura>();
        }
    
        public int AboneId { get; set; }
        public string TCNo { get; set; }
        public string AboneAdi { get; set; }
        public string AboneSoyadi { get; set; }
        public Nullable<bool> AboneDurum { get; set; }
        public Nullable<decimal> DepozitoTutari { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFatura> tblFatura { get; set; }
    }
}
