//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OdemeProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFatura
    {
        public int FaturaId { get; set; }
        public bool FaturaDurum { get; set; }
        public int FaturaTutar { get; set; }
        public int AboneId { get; set; }
        public System.DateTime FaturaTarih { get; set; }
    
        public virtual tblAbone tblAbone { get; set; }
    }
}
